# Generated by Django 5.0.6 on 2024-07-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('ocupacion', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.comuna')),
            ],
        ),
    ]
