# Generated by Django 5.1.3 on 2024-11-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
